### ISSUE TITLE
Create local directory when gettting new jcr content

### ISSUE THREAD

**Issue by cjelger** [Adobe-Marketing-Cloud/tools#10]
Hi,

It would be nice to have the possibility to create the required local directory when geting a new jcr content that does not yet exist locally. Maybe an option like 'repo checkout <jcr_path>.

This would enable 'cherry picking' of any content without having to rely on a first checkout.

Thx in advance
Christophe

**Comment by alexkli** [comment]
So the basic idea might be to combine these steps (from the examples, nr 1):

    mkdir -p jcr_root/apps/project
    repo get jcr_root/apps/project

into one handy command

    repo checkout /apps/project

This would do, for `repo checkout $jcr_path`

1. check if we currently are in a checkout (`jcr_root` ancestor) or current directory has one (`jcr_root` child), i.e. identify as `root_dir`
   * if this path is already checked out, warn & do nothing
   * or just do a `repo get` for it?
   * if this path is not checked out yet, warn and ask user if he wants to continue adding this new path to the existing local "checkout"
2. `cd $root_dir`
3. `mkdir $jcr_path`
4. `cd $jcr_path` (mapped to the right file system path)
5. `repo get .` (preserving force flag from the `checkout` command)
6. after fetching, exit inside this directory, leaving shell there (if that works; might be handy)

Feedback welcome.

**Comment by alexkli** [comment]
Added `repo checkout` command in 3e95d55c90af4c18183a10b0de6b0732a1405219.

Documentation:

```
Usage: repo checkout [opts] [<jcr-path>]

Initially check out <jcr-path> from server on the file system.

This will create a jcr_root folder in the current directory and check
out the <jcr-path> in there. If this is called with a jcr_root or
a jcr_root exists within the current directory, it will detect that
and check out the <jcr-path> in there.

Arguments:
  <jcr-path>         jcr path to checkout (should be a folder)
```

Note after the checkout and the script is finished, the calling shell stays in whatever directory it was. This cannot be changed by a subshell (the script). The example (2) in the help picks up on that by starting with `cd /apps/myproject`.

@cjelger Please try!

**Comment by cjelger** [comment]
@alexkli Thx, I will check that later this week.

**Comment by cjelger** [comment]
Hi @alexkli Sorry for the delay, I finally managed to test the feature. It works fine, except that I first expected to be able to checkout a directory with a relative path, like:

`[.../jcr_root/apps/whatever]$ repo checkout test` FAILS 

to be able to checkout `/apps/whatever/test` but this doesn't work. I have to specify the absolute path:

`[.../jcr_root/apps/whatever]$ repo checkout /apps/whatever/test` WORKS

Is this something you could fix? This appears "more natural" to me when one is already in the right sub-folder under `jcr_root`.

**Comment by alexkli** [comment]
@cjelger If you are within `/apps/whatever` and have done a checkout or get on this before, you would already have the entire subtree. If not, doing `repo get` or more specifically `repo get test` would do the trick, e.g. to get the latest content, as the `get` command supports relative paths (not sure about `../` style though).
