### ISSUE TITLE
repo - windows, intellij not working

### ISSUE THREAD

**Issue by mkovacek** [Adobe-Marketing-Cloud/tools#12]
I'm trying to setup repo tool with IntelliJ on Windows 10, but I'm getting next error:
`Error running 'put': Cannot run program "C:\Program Files (x86)\tools-repo-v1.3\repo\repo" (in directory "C:\development\customers\testi\workspace\my-project"): CreateProcess error=193, %1 is not a valid Win32 application`

I have install cygwin with zip, unzip, curl, rsync packages
And here is picture with my intellj setup [link](http://prntscr.com/fqdi2j)

**Comment by alexkli** [comment]
Looks like Windows (and IntelliJ on Windows) does not understand the [shebang](https://en.m.wikipedia.org/wiki/Shebang_(Unix) and tries to see it as a Windows executable. You probably have to wrap the command with cygwin in the IntelliJ tool setting.

Let me know the result and we can add it to the documentation.

**Comment by mkovacek** [comment]
Hi @alexkli 

thanks for hint, but now I have next erorr:

`C:\cygwin64\bin\bash.exe repo put -f C:\development\customers\testii\workspace\my-project\ui.apps\src\main\content\jcr_root\apps\my-project\components\content\data2
/cygdrive/c/repo/repo: line 47: basename: command not found
uploading /apps/com/dcep/microsites/ppfi/components/content/data2/* to http://localhost:4502
/cygdrive/c/repo/repo: line 580: date: command not found
/cygdrive/c/repo/repo: line 583: mktemp: command not found
/cygdrive/c/repo/repo: line 319: cat: command not found
FIND: Invalid switch
/cygdrive/c/repo/repo: line 296: mkdir: command not found
/cygdrive/c/repo/repo: line 297: mkdir: command not found
/cygdrive/c/repo/repo: line 299: /META-INF/vault/filter.xml: No such file or directory
/cygdrive/c/repo/repo: line 306: /META-INF/vault/properties.xml: No such file or directory
/cygdrive/c/repo/repo: line 597: mkdir: command not found
/cygdrive/c/repo/repo: line 598: rsync: command not found
/cygdrive/c/repo/repo: line 601: rm: command not found
/cygdrive/c/repo/repo: line 346: zip: command not found
/cygdrive/c/repo/repo: line 606: unzip: command not found
/cygdrive/c/repo/repo: line 606: grep: command not found
/cygdrive/c/repo/repo: line 355: curl: command not found
: failed to upload package: 

Process finished with exit code 5`

I have tried all this command in cygwin terminal and they are working

New setup: [link](http://prntscr.com/fqhd9l)

**Comment by mkovacek** [comment]
Finally, works :)

**1. put**
- Program: C:\cygwin64\bin\bash
- Parameters: -l repo put -f $FilePath$

**2. get** 
- Program: C:\cygwin64\bin\bash
- Parameters: -l repo get -f $FilePath$

**3. status** 
- Program: C:\cygwin64\bin\bash
- Parameters: -l repo st $FilePath$

**4. diff** 
- Program: C:\cygwin64\bin\bash
- Parameters: -l repo diff $FilePath$

Only one thing, on the end of execution all commands I'm getting next message:
`clear: terminal attributes: No such device or address`

Is this something that I need be worried about?

**Comment by alexkli** [comment]
Great! Thanks for the commands, I added it to the readme: https://github.com/Adobe-Marketing-Cloud/tools/commit/e2e39ffd688a3e1c62e68b59679d5756b6d8c5e5

Regarding `clear: terminal attributes: No such device or address` - haven't seen this before and not sure what it means. `repo` itself does not call `clear`. Googling finds similar issues that mention different bash installations (e.g. cygwin, git) or versions as a cause, like [this one](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2207). If you find out more and it might need a fix in repo, please create a separate issue (I don't have a Windows readily available to investigate).

Closing this issue as done.
