### ISSUE TITLE
No such file or directory error in IntelliJ using repo

### ISSUE THREAD

**Issue by GonzaloCalandria** [Adobe-Marketing-Cloud/tools#13]
Hello, I'm trying to setup this repo tool in IntelliJ without any luck.

I've downloaded the repo file and is placed at `C:\RepoTool\` folder.
Also installed cygwin and placed at `C:\cygwin64` folder.
I've included the folder `C:\cygwin64` into the PATH environment variable.
Configured the different tools like the tutorial said.
![image](https://user-images.githubusercontent.com/2286280/30217587-fe85e6c6-948c-11e7-89b8-160e3571b80a.png)
But when I try to run the tool it throws 
```
C:\cygwin64\bin\bash.exe -l repo get -f C:\AEM\Projects\wknd-sites-guide\ui.apps\src\main\content\jcr_root\apps\wknd\components
/usr/bin/bash: repo: No such file or directory

Process finished with exit code 127
```

Why is throwing that error?

**Comment by alexkli** [comment]
It can't find `repo`. You have to make sure the location of `repo` is in your `PATH` for cygwin's bash,  i.e. something like

    PATH=C:\RepoTool

(I don't know the exact syntax on cygwin)

Or you use the absolute path to the repo executable instead of just `repo` in the IntelliJ tool configuration., for example:

    -l C:\RepoTool\repo -f $FilePath$

**Comment by GonzaloCalandria** [comment]
Thanks @alexkli that solved the problem (the full path) but now I'm having this errors:
```
downloading /apps/wknd/components/* from http://localhost:4502
        0  09-08-2017 15:51   jcr_root/apps/wknd/components/
        0  09-08-2017 15:51   jcr_root/apps/wknd/components/content/
        0  09-08-2017 15:51   jcr_root/apps/wknd/components/structure/
        0  09-08-2017 15:51   jcr_root/apps/wknd/components/structure/page/
      382  09-08-2017 15:51   jcr_root/apps/wknd/components/structure/page/.content.xml
        0  09-08-2017 15:51   jcr_root/apps/wknd/components/page/
rsync: failed to set permissions on "/cygdrive/c/AEM/Projects/wknd-sites-guide/ui.apps/src/main/content/jcr_root/apps/wknd/components": Permission denied (13)
rsync: failed to set permissions on "/cygdrive/c/AEM/Projects/wknd-sites-guide/ui.apps/src/main/content/jcr_root/apps/wknd/components/content": Permission denied (13)
rsync: failed to set permissions on "/cygdrive/c/AEM/Projects/wknd-sites-guide/ui.apps/src/main/content/jcr_root/apps/wknd/components/page": Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
clear: terminal attributes: No such device or address
```
(I'm using eclipse and intellij to test this)

**Comment by alexkli** [comment]
I don't know for sure. The error is thrown by `rsync` which is used by `repo` to copy file structures from a temporary folder to your repo checkout (or vice versa).

Googling around I found [this as a very similar error case](https://unix.stackexchange.com/questions/12203/rsync-failed-to-set-permissions-on-error-with-rsync-a-or-p-option). Note that you'll find a lot on this error with ssh involved in rsync, which is _not_ the case with `repo`.

`rsync` (and by being called from `repo` and `cygwin`) might be running under a user that does not have permissions on these folders (`/cygdrive/c/AEM/Projects/wknd-sites-guide/ui.apps/src/main/content/jcr_root...`) to change permissions on them.

**Comment by alexkli** [comment]
FYI, I tried to clarify the original problem in the readme: https://github.com/Adobe-Marketing-Cloud/tools/commit/96f7d462de5638d2c5f50315bc9ec0fd56a3a7a0

**Comment by GonzaloCalandria** [comment]
Thanks again for the answers @alexkli 
About the first problem.. I don't know how to include that variable in cygwin $PATH so that's why I used full path. 
About my second problem, I opened Eclipse in admin mode and those problems gone!
The only problem I have now is an error at the end of the command (but it works besides that error) `clear: terminal attributes: No such device or address`.

**Comment by alexkli** [comment]
Someone else saw the `clear: terminal attributes: No such device or address` error as well on Windows/cygwin, and it seems not an actual problem, just a nuisance. See bottom of #12.

I am closing this issue. Let me know if there is anything else that should be done.
