### ISSUE TITLE
repo: does not exists: /apps/foldername

### ISSUE THREAD

**Issue by rajakvk** [Adobe-Marketing-Cloud/tools#15]
Environment:
Windows 10, cygwin64 terminal (with zip, unzip, rsync), localhost:4502 (admin:admin)

repo checkout /apps/foldername
through error
repo: does not exists: /apps/foldername

**Comment by alexkli** [comment]
The `checkout` command will come in version `1.4` which has not been released yet. The message looks like it's a version of `repo` that does not have the `checkout` command.

You can grab the current master [here](https://github.com/Adobe-Marketing-Cloud/tools/blob/master/repo/repo), it's only this one shell script.

I should probably release 1.4 now...

Closing this. Let me know if you have been seeing this with the master version.

**Comment by alexkli** [comment]
FYI, [1.4 release](https://github.com/Adobe-Marketing-Cloud/tools/releases/tag/repo-1.4) is out.
