### ISSUE TITLE
Manual Install Repo

### ISSUE THREAD

**Issue by sai-ui** [Adobe-Marketing-Cloud/tools#27]
Hello,

I've installed Cygwin in my windows, can anyone let me know how to install Repo manually. I've already configured ae
![repo-issue](https://user-images.githubusercontent.com/25843279/69241707-4c03c600-0bc5-11ea-8ac7-1a2e82158523.PNG)
m project in vs code. I'm new to this process so guide me with your thoughts

**Comment by alexkli** [comment]
Installation instructions are here: https://github.com/Adobe-Marketing-Cloud/tools/blob/master/repo/README.md
