### ISSUE TITLE
cannot address namespace prefixed paths such as cq:dialog

### ISSUE THREAD

**Issue by dnlek** [Adobe-Marketing-Cloud/tools#5]
I've tried to use repo tool with cq:dialog file but it is not working.

repo get - didn't download this file
repo diff - shows that whole file is new
repo status - shows that there is no such directory
repo put - shows that upload succeed but nothing changes in aem

However when I ran repo get on folder above it downloaded whole catalog with _cq_dialog inside.

tested with aem 6.1 and repo 1.2.

**Comment by dnlek** [comment]
This issue can be resolved by #6

**Comment by alexkli** [comment]
Thanks for reporting and the PR!

This has been a known issue that all the namespace mapping file vault does (`prefix:*` becomes `_prefix_*` on the filesystem) was not handled by repo yet.

I did a slightly broader fix with more known namespaces and also covered files ending with `.xml` (such as `_cq_editConfig.xml` or `_rep_policy.xml`) in c3c0a0f7f085da4dd6f9766a6d9caf87c34875b4.

**Comment by alexkli** [comment]
Would be great to get some feedback (I tested it only a bit) and then I would release a 1.3 for homebrew. (Maybe including whatever the result of PR #7 will be).

**Comment by alexkli** [comment]
@tripodsan FYI
